config/routes.rb
Rails.application.routes.draw do

    resources :helps
  

end

app/models/need.rb
class Need < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/helps_controller.rb
class HelpsController < ApplicationController
	def index
		@helps = Need.all
	end
	def new
		@need = Need.new
	end
	def create
		need = Need.create(need_params)
    	if @need.save
    		redirect_to helps_path
    	else
    		render "new"
    	end
	end
	def show
		@need = Need.find(params[:id])
	end
	def edit
		@need = Need.find(params[:id])
	end
	def update
		@need = Need.find(params[:id])

    	if @need.update_attributes(need_params)
    		redirect_to helps_path 
    	else
    		render "edit"
    	end
	end
	def destroy
	end
	 def need_params
    	params.require(:need).permit(:Gender, :Age, :health)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/helps_helper.rb
module HelpsHelper
end

app/views/helps/edit.html.erb
<h1> edit need <h1>
 <%= form_for @need do |f| %>

 <p>
   <%= f.label :Gender %><br />
   <%= f.text_field :Gender %><br />
</p>

<p>
   <%= f.label :health %><br />
   <%= f.text_field :health %><br />
</p>
<p>
	 <%= f.label :Age %><br />
   <%= f.text_field :Age %><br />
</p>
<p>
    <%= f.submit "Update post" , :action => :create %>
</p>
<% end %>

app/views/helps/index.html.erb
<h1> Help! </h1>
<h2><%= link_to "new" ,new_help_path %></h2>
	<hr/>
	<hr/>
<% @helps.each do |need| %>
<h2><%= link_to need.name , help_path(need) %></h2>


 <hr />

<% end %>

	

app/views/helps/new.html.erb
<h1> Add a new need </h1>
<%= form_for @help do |f| %>

<p> 
   <%= f.label :Gender %><br />
   <%= f.text_field :Gender %><br />
</p>
<p>
   <%= f.label :Age %><br />
   <%= f.text_field :Age %><br />
</p>
<p>
   <%= f.label :health %><br />
   <%= f.text_field :health %><br />
</p>

<p>
    <%= f.submit "Add a new need" %>
</p>
<% end %>

app/views/helps/show.html.erb
<p><%= @need.Gender %><p>
<p><%= @need.Age %></p>
<p><%= @need.health %></p>
<small><%= @need.created_at %></small>
<p><%= link_to "Edit", edit_help_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Help</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>